# Javascript Node CircleCI 2.0 configuration file
# .circleci/config.yml
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

workflows:
  version: 2
  test:
    jobs:
      # https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462/2
      - test-LTS

# a collection of steps
jobs:
  test-LTS: &test-template
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images
      - image: circleci/node:10.9.0-stretch
    steps:
      - checkout
      - run: # run tests
          name: test
          command: npm test

  test-latest:
    docker:
      - image: circleci/node:11.8.0-stretch
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
